function [voltageBreakpoints, temperatureBreakpoints, ...
        irradianceBreakpoints, currentTable] = ...
        pvbatt_generate_pv_lookup(p)
%PVBATT_GENERATE_PV_LOOKUP Generate a standard-block PV current table.
% The nonlinear one-diode equation is solved offline. During simulation the
% plant uses an n-D Lookup Table block rather than a MATLAB Function block.

voltageBreakpoints = 0:2:380;
temperatureBreakpoints = [0, 15, 25, 35, 45, 60, 75];
irradianceBreakpoints = [0, 100, 200, 400, 600, 800, 1000, 1200];

currentTable = zeros( ...
    numel(voltageBreakpoints), ...
    numel(temperatureBreakpoints), ...
    numel(irradianceBreakpoints));

for kG = 1:numel(irradianceBreakpoints)
    irradiance = irradianceBreakpoints(kG);
    for kT = 1:numel(temperatureBreakpoints)
        temperatureC = temperatureBreakpoints(kT);
        for kV = 1:numel(voltageBreakpoints)
            arrayVoltage = voltageBreakpoints(kV);
            currentTable(kV, kT, kG) = localArrayCurrent( ...
                arrayVoltage, temperatureC, irradiance, p);
        end
    end
end
end

function arrayCurrent = localArrayCurrent( ...
        arrayVoltage, temperatureC, irradiance, p)
if irradiance <= 0
    arrayCurrent = 0;
    return;
end

boltzmann = 1.380649e-23;
electronCharge = 1.602176634e-19;
temperatureK = temperatureC + 273.15;
referenceTemperatureK = p.pv.referenceTemperatureC + 273.15;
bandGapJoule = p.pv.bandGapElectronVolt * electronCharge;

photocurrent = irradiance / p.pv.referenceIrradiance ...
    * (p.pv.photocurrentSTC ...
    + p.pv.shortCircuitTempCoefficient ...
    * (temperatureC - p.pv.referenceTemperatureC));

saturationCurrent = p.pv.saturationCurrentSTC ...
    * (temperatureK / referenceTemperatureK)^3 ...
    * exp(bandGapJoule ...
    / (p.pv.diodeIdeality * boltzmann) ...
    * (1 / referenceTemperatureK - 1 / temperatureK));

moduleVoltage = arrayVoltage / p.pv.seriesModules;
thermalVoltage = p.pv.cellsPerModule ...
    * boltzmann * temperatureK / electronCharge;

moduleCurrent = max(photocurrent, 0);
for iteration = 1:20
    diodeArgument = (moduleVoltage ...
        + moduleCurrent * p.pv.seriesResistance) ...
        / (p.pv.diodeIdeality * thermalVoltage);
    diodeArgument = min(diodeArgument, 60);
    exponentialTerm = exp(diodeArgument);

    residual = moduleCurrent - photocurrent ...
        + saturationCurrent * (exponentialTerm - 1) ...
        + (moduleVoltage ...
        + moduleCurrent * p.pv.seriesResistance) ...
        / p.pv.shuntResistance;
    derivative = 1 ...
        + saturationCurrent * exponentialTerm ...
        * p.pv.seriesResistance ...
        / (p.pv.diodeIdeality * thermalVoltage) ...
        + p.pv.seriesResistance / p.pv.shuntResistance;

    moduleCurrent = moduleCurrent - residual / derivative;
    moduleCurrent = min(max(moduleCurrent, 0), 1.2 * photocurrent);
end

arrayCurrent = p.pv.parallelStrings * moduleCurrent;
end
