function current = pvbatt_pv_current(voltage, temperatureC, irradiance)
%PVBATT_PV_CURRENT Interpolate the precomputed PV array current table.

global PVBATT_PV_VOLTAGE_BP PVBATT_PV_TEMPERATURE_BP %#ok<GVMIS>
global PVBATT_PV_IRRADIANCE_BP PVBATT_PV_CURRENT_TABLE %#ok<GVMIS>

voltage = min(max(voltage, PVBATT_PV_VOLTAGE_BP(1)), ...
    PVBATT_PV_VOLTAGE_BP(end));
temperatureC = min(max(temperatureC, ...
    PVBATT_PV_TEMPERATURE_BP(1)), ...
    PVBATT_PV_TEMPERATURE_BP(end));
irradiance = min(max(irradiance, PVBATT_PV_IRRADIANCE_BP(1)), ...
    PVBATT_PV_IRRADIANCE_BP(end));

current = interpn( ...
    PVBATT_PV_VOLTAGE_BP, ...
    PVBATT_PV_TEMPERATURE_BP, ...
    PVBATT_PV_IRRADIANCE_BP, ...
    PVBATT_PV_CURRENT_TABLE, ...
    voltage, temperatureC, irradiance, 'linear');
end
