function [x0, u0, w0, info] = phase1_operating_point( ...
        p, loadPower, initialStateOfCharge, temperatureC, irradiance)
%PHASE1_OPERATING_POINT Construct a consistent averaged-model operating point.
%   Electrical derivatives are zero at the returned operating point.
%   SoC may change if the battery is charging or discharging.

arguments
    p (1, 1) struct
    loadPower (1, 1) double {mustBePositive}
    initialStateOfCharge (1, 1) double ...
        {mustBeGreaterThanOrEqual(initialStateOfCharge, 0), ...
        mustBeLessThanOrEqual(initialStateOfCharge, 1)}
    temperatureC (1, 1) double
    irradiance (1, 1) double {mustBeNonnegative}
end

dcBusVoltage = p.dcBus.referenceVoltage;
temperatureOffset = temperatureC - p.pv.referenceTemperatureC;
irradianceRatio = max( ...
    irradiance / p.pv.referenceIrradiance, ...
    p.pv.minimumIrradianceRatio);

moduleMppVoltage = p.pv.moduleMaximumPowerVoltage ...
    + 0.88 * p.pv.openCircuitVoltageTempCoefficient ...
    * temperatureOffset ...
    + 0.8 * p.pv.openCircuitVoltageLogCoefficient ...
    * log(irradianceRatio);
pvVoltage = p.pv.seriesModules * max(moduleMppVoltage, 1);
pvCurrent = phase1_pv_current( ...
    pvVoltage, temperatureC, irradiance, p);
pvInductorCurrent = pvCurrent;

oneMinusPvDuty = (pvVoltage ...
    - p.pvConverter.inductorResistance * pvInductorCurrent) ...
    / dcBusVoltage;
pvDuty = 1 - oneMinusPvDuty;

loadCurrent = loadPower / dcBusVoltage;
pvBusCurrent = oneMinusPvDuty * pvInductorCurrent;
requiredBatteryBusCurrent = loadCurrent - pvBusCurrent;

batteryInternalVoltage = p.battery.nominalVoltage ...
    + p.battery.ocvSlope ...
    * (initialStateOfCharge - p.battery.nominalStateOfCharge);
combinedBatteryResistance = p.battery.internalResistance ...
    + p.batteryConverter.inductorResistance;
discriminant = batteryInternalVoltage^2 ...
    - 4 * combinedBatteryResistance * dcBusVoltage ...
    * requiredBatteryBusCurrent;
if discriminant < 0
    error("Phase1:OperatingPointUnavailable", ...
        "Requested load cannot be supplied at the assumed operating point.");
end

batteryInductorCurrent = (batteryInternalVoltage ...
    - sqrt(discriminant)) / (2 * combinedBatteryResistance);
batteryTerminalVoltage = batteryInternalVoltage ...
    - p.battery.internalResistance * batteryInductorCurrent;
oneMinusBatteryDuty = (batteryTerminalVoltage ...
    - p.batteryConverter.inductorResistance ...
    * batteryInductorCurrent) / dcBusVoltage;
batteryDuty = 1 - oneMinusBatteryDuty;

if pvDuty < p.limits.minimumDuty || pvDuty > p.limits.maximumDuty ...
        || batteryDuty < p.limits.minimumDuty ...
        || batteryDuty > p.limits.maximumDuty
    error("Phase1:DutyOutsideLimits", ...
        "The calculated operating point requires an invalid duty ratio.");
end

loadResistance = dcBusVoltage^2 / loadPower;
x0 = [ ...
    pvVoltage; ...
    pvInductorCurrent; ...
    batteryTerminalVoltage; ...
    batteryInductorCurrent; ...
    initialStateOfCharge; ...
    dcBusVoltage];
u0 = [pvDuty; batteryDuty];
w0 = [temperatureC; irradiance; loadResistance];

[dx, aux] = Plant_Derivatives(x0, u0, w0, p);
info.electricalDerivative = dx([1:4, 6]);
info.socDerivative = dx(5);
info.aux = aux;
info.pvArrayRatedPower = p.pv.seriesModules ...
    * p.pv.parallelStrings * p.pv.moduleMaximumPower;
end
