function modelFile = build_pvess_template()
%BUILD_PVESS_TEMPLATE Build the paper-scale switching power-circuit template.

thisDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(thisDir);
modelDir = fullfile(projectRoot,'models');
if ~exist(modelDir,'dir')
    mkdir(modelDir);
end
addpath(thisDir);
cfg = pvess_init(false);

model = 'PV_ESS_MPC_Switching_Template';
modelFile = fullfile(modelDir,[model '.slx']);
bdclose('all');
new_system(model);
open_system(model);

libs = {'spspowerguiLib','spsPVArrayLib','spsBatteryLib', ...
    'spsBoostConverterLib','spsTwoQuadrantDCDCConverterLib', ...
    'spsUniversalBridgeLib','spsThreePhaseSourceLib', ...
    'spsThreePhaseBreakerLib','spsThreePhaseVIMeasurementLib', ...
    'spsThreePhaseSeriesRLCBranchLib','spsThreePhaseParallelRLCLoadLib', ...
    'spsThreePhaseTransformerTwoWindingsLib','spsSeriesRLCBranchLib', ...
    'spsParallelRLCBranchLib','spsCurrentMeasurementLib', ...
    'spsVoltageMeasurementLib','spsVariableResistorLib', ...
    'spsPWMGeneratorDCDCLib','spsGroundLib','spsBreakerLib'};
for k = 1:numel(libs)
    load_system(libs{k});
end

sfPath = ['simulink/User-Defined' newline 'Functions/Level-2 MATLAB' newline ...
    'S-Function'];
viPath = ['spsThreePhaseVIMeasurementLib/Three-Phase' newline 'V-I Measurement'];
rlc3Path = ['spsThreePhaseSeriesRLCBranchLib/Three-Phase' newline 'Series RLC Branch'];
load3Path = ['spsThreePhaseParallelRLCLoadLib/Three-Phase' newline 'Parallel RLC Load'];
trPath = ['spsThreePhaseTransformerTwoWindingsLib/Three-Phase' newline ...
    'Transformer' newline '(Two Windings)'];
pwmPath = ['spsPWMGeneratorDCDCLib/PWM Generator' newline '(DC-DC)'];
batLegPath = ['spsTwoQuadrantDCDCConverterLib/Two-Quadrant' newline ...
    'DC//DC Converter'];

%% Model-level configuration and saved model workspace
set_param(model,'SolverType','Fixed-step','Solver','ode3', ...
    'FixedStep','Ts_power','StopTime','0.01', ...
    'ReturnWorkspaceOutputs','on','SignalLogging','off');
set_param(model,'PreLoadFcn',sprintf('addpath(''%s'');',strrep(thisDir,'\','/')));
mw = get_param(model,'ModelWorkspace');
names = fieldnames(cfg);
for k = 1:numel(names)
    assignin(mw,names{k},cfg.(names{k}));
end
% The saved template opens all three commissioning isolators. This makes a
% direct press of Run a safe structural smoke test. run_paper_scenario()
% overrides these model-workspace values and closes the complete topology.
assignin(mw,'PV_connect',0);
assignin(mw,'Battery_connect',0);
assignin(mw,'Inverter_connect',0);
assignin(mw,'PV_blocking',1);
assignin(mw,'Battery_blocking',1);
assignin(mw,'Inverter_enable',0);

add_block('spspowerguiLib/powergui',[model '/powergui'], ...
    'Position',[25 25 115 65],'SimulationMode','Discrete', ...
    'SampleTime','Ts_power','x0status','blocks', ...
    'SolverType','Tustin/Backward Euler (TBE)');

%% PV array and switching boost converter (paper Fig. 2)
add_block('spsPVArrayLib/PV Array',[model '/PV_Array'], ...
    'Position',[55 210 145 320],'Npar','Np_pv','Nser','Ns_pv', ...
    'ModuleName','SunPower SPR-305E-WHT-D','BAL','on', ...
    'Tc','Ts_power','Tfilter','5e-5');
add_block('simulink/Sources/From Workspace',[model '/Irradiance_Profile'], ...
    'VariableName','G_profile','Position',[30 130 135 160]);
add_block('simulink/Sources/Constant',[model '/PV_Temperature'], ...
    'Value','25','Position',[55 170 105 195]);
add_block('simulink/Sinks/Terminator',[model '/PV_Measurement_Term'], ...
    'Position',[155 210 175 230]);
add_block('spsParallelRLCBranchLib/Parallel RLC Branch',[model '/Cpv'], ...
    'Position',[175 270 235 330],'BranchType','C', ...
    'Capacitance','Cpv','Setx0','on','InitialVoltage','Vpv0');
add_block('spsVoltageMeasurementLib/Voltage Measurement',[model '/Vpv_Measurement'], ...
    'Position',[175 220 225 255]);
add_block('spsCurrentMeasurementLib/Current Measurement',[model '/Ipv_Measurement'], ...
    'Position',[170 185 225 210]);
add_block('spsSeriesRLCBranchLib/Series RLC Branch',[model '/Lpv'], ...
    'Position',[255 185 340 210],'BranchType','RL', ...
    'Resistance','RLpv','Inductance','Lpv','SetiL0','on', ...
    'InitialCurrent','ILpv0');
add_block('spsBreakerLib/Breaker',[model '/PV_Isolator'], ...
    'Position',[345 180 370 215],'InitialState','1','External','on', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6','SnubberCapacitance','inf');
add_block('simulink/Sources/Constant',[model '/PV_Connect'], ...
    'Value','PV_connect','Position',[300 145 340 165]);
add_block('spsBoostConverterLib/Boost Converter',[model '/PV_Boost'], ...
    'Position',[375 165 465 255],'ModelType','Switching devices', ...
    'Ron','Ron_switch','Rs','1e6','Cs','inf','Vforward','[0,0]', ...
    'Ron_Diode','Ron_switch','Rs_Diode','1e6','Cs_Diode','inf', ...
    'Vf_Diode','Vf_diode');
add_block('simulink/Signal Routing/Mux',[model '/MPPT_Input_Mux'], ...
    'Inputs','3','Position',[230 95 235 145]);
add_block(sfPath,[model '/IncCond_MPPT'], ...
    'FunctionName','pvess_mppt_sfun', ...
    'Parameters','Ts_mppt,Dpv0,Dpv_min,Dpv_max,Dpv_step,Dpv_off_mppt', ...
    'Position',[255 95 355 145]);
add_block(pwmPath,[model '/PV_PWM'], ...
    'Position',[375 90 460 135],'Fsw','Fsw_pv','Ts','Ts_power');
add_block('simulink/Sources/Constant',[model '/PV_Blocking'], ...
    'Value','PV_blocking','Position',[380 140 420 160]);
add_block('simulink/Math Operations/Product',[model '/PV_Power'], ...
    'Position',[255 225 300 255]);

%% Common DC bus, capacitor and switchable DC loads
add_block('spsParallelRLCBranchLib/Parallel RLC Branch',[model '/Cdc'], ...
    'Position',[525 255 585 325],'BranchType','C', ...
    'Capacitance','Cdc','Setx0','on','InitialVoltage','Vdc0');
add_block('spsBreakerLib/Breaker',[model '/PV_DC_Isolator'], ...
    'Position',[475 210 500 245],'InitialState','1','External','on', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6','SnubberCapacitance','inf');
add_block('spsBreakerLib/Breaker',[model '/Battery_DC_Isolator'], ...
    'Position',[855 175 880 210],'InitialState','1','External','on', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6','SnubberCapacitance','inf');
add_block('spsBreakerLib/Breaker',[model '/Inverter_DC_Isolator'], ...
    'Position',[490 470 515 505],'InitialState','1','External','on', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6','SnubberCapacitance','inf');
add_block('simulink/Sources/Constant',[model '/Inverter_Connect'], ...
    'Value','Inverter_connect','Position',[430 455 480 475]);
add_block('spsVoltageMeasurementLib/Voltage Measurement',[model '/Vdc_Measurement'], ...
    'Position',[605 255 660 305]);
add_block('spsCurrentMeasurementLib/Current Measurement',[model '/Idc1_Measurement'], ...
    'Position',[680 250 730 275]);
add_block('spsVariableResistorLib/Variable Resistor',[model '/DC_Load_0p6MW'], ...
    'Position',[755 245 830 295],'Rabsmin','0.2');
add_block('simulink/Sources/From Workspace',[model '/Rdc1_Profile'], ...
    'VariableName','Rdc1_profile','Position',[680 205 785 230]);
add_block('spsCurrentMeasurementLib/Current Measurement',[model '/Idc2_Measurement'], ...
    'Position',[680 335 730 360]);
add_block('spsVariableResistorLib/Variable Resistor',[model '/DC_Load_1MW'], ...
    'Position',[755 330 830 380],'Rabsmin','0.2');
add_block('simulink/Sources/From Workspace',[model '/Rdc2_Profile'], ...
    'VariableName','Rdc2_profile','Position',[680 395 785 420]);
add_block('simulink/Math Operations/Sum',[model '/Idc_Load_Sum'], ...
    'Inputs','++','Position',[745 305 775 325]);
add_block('simulink/Math Operations/Product',[model '/DC_Load_Power'], ...
    'Position',[805 300 850 330]);
add_block('spsGroundLib/Ground',[model '/DC_Ground'], ...
    'Position',[505 390 530 420]);

%% Battery and bidirectional buck-boost converter (paper Fig. 5 and 7)
add_block(batLegPath,[model '/Battery_Leg'], ...
    'Position',[905 165 1005 260],'ModelType','Switching devices', ...
    'Ron','Ron_switch','Rs','1e6','Cs','inf','Vforward','[0,0]', ...
    'Ron_Diode','Ron_switch','Rs_Diode','1e6','Cs_Diode','inf', ...
    'Vf_Diode','0');
add_block('spsSeriesRLCBranchLib/Series RLC Branch',[model '/Lbat'], ...
    'Position',[1035 185 1120 210],'Orientation','left', ...
    'BranchType','RL','Resistance','RLbat','Inductance','Lbat', ...
    'SetiL0','on','InitialCurrent','Ibat0');
add_block('spsBreakerLib/Breaker',[model '/Battery_Isolator'], ...
    'Position',[1010 180 1030 215],'InitialState','1','External','on', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6','SnubberCapacitance','inf');
add_block('simulink/Sources/Constant',[model '/Battery_Connect'], ...
    'Value','Battery_connect','Position',[970 285 1015 305]);
add_block('spsCurrentMeasurementLib/Current Measurement',[model '/Ibat_Measurement'], ...
    'Position',[1145 185 1200 210],'Orientation','left');
add_block('spsBatteryLib/Battery',[model '/Battery'], ...
    'Position',[1235 165 1325 270],'BatType','Lithium-Ion', ...
    'NomV','V_bat_nom','NomQ','Q_bat_Ah','SOC','SOC0','Batt_Tr','1', ...
    'PresetModel','off','MaxQ','Q_bat_Ah','MinV','270','FullV','330', ...
    'Dis_rate','650','R','R_bat_internal','Normal_OP','1170', ...
    'expZone','[315,65]');
add_block('simulink/Sinks/Terminator',[model '/Battery_Measurement_Term'], ...
    'Position',[1335 175 1355 195]);
add_block('simulink/Math Operations/Gain',[model '/SOC_Coulomb_Gain'], ...
    'Gain','-100/(3600*Q_bat_Ah)','Position',[1125 300 1225 330]);
add_block('simulink/Discrete/Discrete-Time Integrator',[model '/SOC_Integrator'], ...
    'gainval','1','SampleTime','Ts_bat_ctrl','InitialCondition','SOC0', ...
    'LimitOutput','on','UpperSaturationLimit','100', ...
    'LowerSaturationLimit','0','Position',[1245 295 1315 335]);
add_block('simulink/Signal Routing/Mux',[model '/Battery_Control_Mux'], ...
    'Inputs','5','Position',[875 45 880 125]);
add_block(sfPath,[model '/Battery_Controller'], ...
    'FunctionName','pvess_battery_sfun', ...
    'Parameters',['Ts_bat_ctrl,Vdc_ref,SOC_min,SOC_max,Ibat_max,' ...
    'Kpv_bat,Kiv_bat,Kpi_bat,Kii_bat,V_bat_nom,Db_min,Db_max'], ...
    'Position',[905 45 1035 125]);
add_block('simulink/Signal Routing/Demux',[model '/Battery_Ctrl_Demux'], ...
    'Outputs','[1 1]','Position',[1050 55 1055 115]);
add_block(pwmPath,[model '/Battery_PWM'], ...
    'Position',[1080 50 1165 95],'Fsw','Fsw_bat','Ts','Ts_power');
add_block('simulink/Logic and Bit Operations/Logical Operator',[model '/Battery_NOT'], ...
    'Operator','NOT','Position',[1180 35 1225 65]);
add_block('simulink/Discrete/Unit Delay',[model '/Upper_Delay'], ...
    'SampleTime','Ts_power','InitialCondition','0','Position',[1240 25 1295 55]);
add_block('simulink/Logic and Bit Operations/Logical Operator',[model '/Upper_AND'], ...
    'Operator','AND','Inputs','2','Position',[1310 25 1355 60]);
add_block('simulink/Discrete/Unit Delay',[model '/Lower_Delay'], ...
    'SampleTime','Ts_power','InitialCondition','0','Position',[1240 80 1295 110]);
add_block('simulink/Logic and Bit Operations/Logical Operator',[model '/Lower_AND'], ...
    'Operator','AND','Inputs','2','Position',[1310 78 1355 113]);
add_block('simulink/Signal Routing/Mux',[model '/Battery_Gate_Mux'], ...
    'Inputs','2','Position',[1375 42 1380 105]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model '/Battery_Gate_Double'], ...
    'OutDataTypeStr','double','Position',[1395 60 1465 90]);
add_block('simulink/Sources/Constant',[model '/Battery_Blocking'], ...
    'Value','Battery_blocking','Position',[905 275 945 295]);

%% Three-phase interlinking converter and LC filter (paper Fig. 6)
add_block('spsUniversalBridgeLib/Universal Bridge',[model '/Interlinking_Converter'], ...
    'Position',[510 515 610 645],'Arms','3','Device','IGBT / Diodes', ...
    'SnubberResistance','1e5','SnubberCapacitance','inf', ...
    'Ron','Ron_switch','ForwardVoltages','[Vf_diode,Vf_diode]');
add_block(rlc3Path,[model '/Filter_Lf_Rf'], ...
    'Position',[650 545 760 615],'BranchType','RL', ...
    'Resistance','Rf','Inductance','Lf');
add_block(viPath,[model '/Filter_VI'], ...
    'Position',[790 535 895 625],'VoltageMeasurement','phase-to-ground', ...
    'CurrentMeasurement','yes');
add_block(load3Path,[model '/Filter_Cf'], ...
    'Position',[920 650 1015 725],'Configuration','Y (grounded)', ...
    'NominalVoltage','Vac_ll','NominalFrequency','f_grid', ...
    'ActivePower','0','InductivePower','0', ...
    'CapacitivePower','2*pi*f_grid*Cf*Vac_ll^2','LoadType','constant Z');

% AC loads: 0.5 MW base plus a switched 0.5 MW branch.
add_block(viPath,[model '/Load_VI'], ...
    'Position',[940 515 1045 605],'VoltageMeasurement','phase-to-ground', ...
    'CurrentMeasurement','yes');
add_block(load3Path,[model '/AC_Load_Base'], ...
    'Position',[1090 500 1190 570],'Configuration','Y (grounded)', ...
    'NominalVoltage','Vac_ll','NominalFrequency','f_grid', ...
    'ActivePower','P_ac_base','InductivePower','0','CapacitivePower','0', ...
    'LoadType','constant Z');
add_block('spsThreePhaseBreakerLib/Three-Phase Breaker',[model '/AC_Load_Step_Breaker'], ...
    'Position',[1085 600 1175 665],'InitialState','open', ...
    'SwitchTimes','T_ac_step','External','off','BreakerResistance','1e-3', ...
    'SnubberResistance','1e6','SnubberCapacitance','inf');
add_block(load3Path,[model '/AC_Load_Step'], ...
    'Position',[1205 595 1305 665],'Configuration','Y (grounded)', ...
    'NominalVoltage','Vac_ll','NominalFrequency','f_grid', ...
    'ActivePower','P_ac_step','InductivePower','0','CapacitivePower','0', ...
    'LoadType','constant Z');

% Equivalent low-voltage grid connection through the paper's 2.5 MVA transformer.
add_block('spsThreePhaseBreakerLib/Three-Phase Breaker',[model '/Grid_Breaker'], ...
    'Position',[935 775 1025 840],'InitialState','open', ...
    'SwitchTimes','T_grid_connect','External','off', ...
    'BreakerResistance','1e-3','SnubberResistance','1e6', ...
    'SnubberCapacitance','inf');
add_block(viPath,[model '/Grid_VI'], ...
    'Position',[1050 760 1155 850],'VoltageMeasurement','phase-to-ground', ...
    'CurrentMeasurement','yes');
add_block(trPath,[model '/Grid_Transformer'], ...
    'Position',[1190 750 1320 860],'Winding1Connection','Yg', ...
    'Winding2Connection','Yg','UNITS','pu','NominalPower','[S_tr,f_grid]', ...
    'Winding1','[V_tr_lv,0.002,0.06]','Winding2','[V_tr_hv,0.002,0.06]', ...
    'Rm','500','Lm','500');
add_block('spsThreePhaseSourceLib/Three-Phase Source',[model '/Utility_25kV'], ...
    'Position',[1370 765 1470 850],'InternalConnection','Yg', ...
    'Voltage','V_tr_hv','Frequency','f_grid','PhaseAngle','0', ...
    'NonIdealSource','on','SpecifyImpedance','off', ...
    'ShortCircuitLevel','S_sc_grid','BaseVoltage','V_tr_hv','XRratio','XR_grid');

%% FCS MPVC/MPPC, synchronization and active/reactive references
add_block('simulink/Sources/Step',[model '/Grid_Connected'], ...
    'Time','T_grid_connect','Before','0','After','1', ...
    'SampleTime','Ts_mpc','Position',[25 505 95 535]);
add_block('simulink/Sources/Step',[model '/Grid_Synchronization'], ...
    'Time','T_sync','Before','0','After','1', ...
    'SampleTime','Ts_mpc','Position',[25 550 95 580]);
add_block('simulink/Sources/Sine Wave',[model '/Vref_A'], ...
    'Amplitude','sqrt(2)*Vac_ll/sqrt(3)','Frequency','2*pi*f_grid', ...
    'Phase','0','SampleTime','Ts_mpc','Position',[130 490 205 520]);
add_block('simulink/Sources/Sine Wave',[model '/Vref_B'], ...
    'Amplitude','sqrt(2)*Vac_ll/sqrt(3)','Frequency','2*pi*f_grid', ...
    'Phase','-2*pi/3','SampleTime','Ts_mpc','Position',[130 530 205 560]);
add_block('simulink/Sources/Sine Wave',[model '/Vref_C'], ...
    'Amplitude','sqrt(2)*Vac_ll/sqrt(3)','Frequency','2*pi*f_grid', ...
    'Phase','2*pi/3','SampleTime','Ts_mpc','Position',[130 570 205 600]);
add_block('simulink/Signal Routing/Mux',[model '/Internal_Vref_Mux'], ...
    'Inputs','3','Position',[225 500 230 595]);
add_block('simulink/Signal Routing/Switch',[model '/Synchronization_Reference_Select'], ...
    'Criteria','u2 ~= 0','Threshold','0.5','Position',[270 535 340 585]);

add_block('simulink/Sources/Constant',[model '/Vdc_Reference'], ...
    'Value','Vdc_ref','Position',[35 650 95 680]);
add_block('simulink/Math Operations/Sum',[model '/Vdc_Error'], ...
    'Inputs','+-','Position',[125 645 155 685]);
add_block('simulink/Math Operations/Product',[model '/Enable_Pref_Integrator'], ...
    'Position',[180 650 225 680]);
add_block('simulink/Math Operations/Gain',[model '/Pref_Proportional'], ...
    'Gain','Kp_dc','Position',[245 630 310 660]);
add_block('simulink/Discrete/Discrete-Time Integrator',[model '/Pref_Integral'], ...
    'gainval','Ki_dc','SampleTime','Ts_mpc','InitialCondition','0', ...
    'LimitOutput','on','UpperSaturationLimit','Pref_max', ...
    'LowerSaturationLimit','Pref_min','Position',[245 675 315 710]);
add_block('simulink/Math Operations/Sum',[model '/Pref_PI_Sum'], ...
    'Inputs','++','Position',[340 645 370 690]);
add_block('simulink/Discontinuities/Saturation',[model '/Pref_Saturation'], ...
    'UpperLimit','Pref_max','LowerLimit','Pref_min', ...
    'Position',[390 650 455 685]);
add_block('simulink/Sources/From Workspace',[model '/Grid_Voltage_Pu_Profile'], ...
    'VariableName','GridVpu_profile','Position',[30 725 145 755]);
add_block('simulink/Math Operations/Bias',[model '/Grid_Pu_Minus_One'], ...
    'Bias','-1','Position',[170 725 225 755]);
add_block('simulink/Math Operations/Gain',[model '/Reactive_Power_Coefficient'], ...
    'Gain','m_var','Position',[250 725 325 755]);

add_block('simulink/Signal Routing/Mux',[model '/FCS_Input_Mux'], ...
    'Inputs','9','Position',[360 455 365 590]);
add_block(sfPath,[model '/MPVC_MPPC_FCS'], ...
    'FunctionName','pvess_fcs_sfun', ...
    'Parameters','Ts_mpc,Lf,Cf,Rf,P_base_mpc,Q_base_mpc,lambda_sw', ...
    'Position',[390 470 505 570]);
add_block('simulink/Signal Routing/Demux',[model '/FCS_Output_Demux'], ...
    'Outputs','[6 1 1]','Position',[520 475 525 565]);
add_block('simulink/Sources/Constant',[model '/Inverter_Enable'], ...
    'Value','Inverter_enable','Position',[535 440 585 465]);
add_block('simulink/Math Operations/Product',[model '/Inverter_Gate_Enable'], ...
    'Position',[545 475 590 515]);
add_block('simulink/Signal Attributes/Data Type Conversion',[model '/Inverter_Gate_Double'], ...
    'OutDataTypeStr','double','Position',[605 480 680 510]);

%% EMS measurements and controller (paper Fig. 9)
add_block('simulink/Math Operations/Dot Product',[model '/AC_Load_Power'], ...
    'Position',[1080 440 1145 470]);
add_block('simulink/Signal Routing/Mux',[model '/EMS_Input_Mux'], ...
    'Inputs','5','Position',[665 445 670 515]);
add_block(sfPath,[model '/EMS_Fig9'], ...
    'FunctionName','pvess_ems_sfun','Parameters','SOC_min,SOC_max', ...
    'Position',[695 445 790 515]);
add_block('simulink/Signal Routing/Demux',[model '/EMS_Output_Demux'], ...
    'Outputs','3','Position',[810 445 815 515]);

%% Logging blocks
logBlock(model,'log_Vdc','Vdc_log',[620 340 690 365]);
logBlock(model,'log_Vpv','Vpv_log',[180 350 250 375]);
logBlock(model,'log_Ipv','Ipv_log',[260 350 330 375]);
logBlock(model,'log_Ibat','Ibat_log',[1130 350 1200 375]);
logBlock(model,'log_SOC','SOC_log',[1245 350 1315 375]);
logBlock(model,'log_Vcabc','Vcabc_log',[800 650 880 675]);
logBlock(model,'log_Ifabc','Ifabc_log',[800 690 880 715]);
logBlock(model,'log_Vgabc','Vgabc_log',[1050 880 1130 905]);
logBlock(model,'log_Igabc','Igabc_log',[1150 880 1230 905]);
logBlock(model,'log_Pref','Pref_log',[390 705 460 730]);
logBlock(model,'log_Qref','Qref_log',[345 735 415 760]);
logBlock(model,'log_Gates','Gate_log',[545 530 620 555]);
logBlock(model,'log_EMS','EMS_log',[835 445 905 470]);
logBlock(model,'log_IbatRef','IbatRef_log',[1070 120 1145 145]);
logBlock(model,'log_FCSCost','FCSCost_log',[535 565 610 590]);
logBlock(model,'log_FCSState','FCSState_log',[625 565 705 590]);
logBlock(model,'log_LoadShed','LoadShed_log',[835 485 915 510]);

%% Simulink signal wiring
sl(model,'Irradiance_Profile/1','PV_Array/1');
sl(model,'PV_Temperature/1','PV_Array/2');
sl(model,'PV_Array/1','PV_Measurement_Term/1');
sl(model,'Vpv_Measurement/1','MPPT_Input_Mux/1');
sl(model,'Ipv_Measurement/1','MPPT_Input_Mux/2');
sl(model,'EMS_Output_Demux/2','MPPT_Input_Mux/3');
sl(model,'MPPT_Input_Mux/1','IncCond_MPPT/1');
sl(model,'IncCond_MPPT/1','PV_PWM/1');
sl(model,'PV_PWM/1','PV_Boost/1');
sl(model,'PV_Blocking/1','PV_Boost/2');
sl(model,'PV_Connect/1','PV_Isolator/1');
sl(model,'PV_Connect/1','PV_DC_Isolator/1');
sl(model,'Vpv_Measurement/1','PV_Power/1');
sl(model,'Ipv_Measurement/1','PV_Power/2');
sl(model,'Rdc1_Profile/1','DC_Load_0p6MW/1');
sl(model,'Rdc2_Profile/1','DC_Load_1MW/1');
sl(model,'Idc1_Measurement/1','Idc_Load_Sum/1');
sl(model,'Idc2_Measurement/1','Idc_Load_Sum/2');
sl(model,'Vdc_Measurement/1','DC_Load_Power/1');
sl(model,'Idc_Load_Sum/1','DC_Load_Power/2');
sl(model,'Battery/1','Battery_Measurement_Term/1');
sl(model,'Ibat_Measurement/1','SOC_Coulomb_Gain/1');
sl(model,'SOC_Coulomb_Gain/1','SOC_Integrator/1');
sl(model,'Grid_Connected/1','Battery_Control_Mux/1');
sl(model,'Vdc_Measurement/1','Battery_Control_Mux/2');
sl(model,'Ibat_Measurement/1','Battery_Control_Mux/3');
sl(model,'SOC_Integrator/1','Battery_Control_Mux/4');
sl(model,'EMS_Output_Demux/1','Battery_Control_Mux/5');
sl(model,'Battery_Control_Mux/1','Battery_Controller/1');
sl(model,'Battery_Controller/1','Battery_Ctrl_Demux/1');
sl(model,'Battery_Ctrl_Demux/1','Battery_PWM/1');
sl(model,'Battery_Ctrl_Demux/2','log_IbatRef/1');
sl(model,'Battery_PWM/1','Battery_NOT/1');
sl(model,'Battery_NOT/1','Upper_Delay/1');
sl(model,'Battery_NOT/1','Upper_AND/1');
sl(model,'Upper_Delay/1','Upper_AND/2');
sl(model,'Battery_PWM/1','Lower_Delay/1');
sl(model,'Battery_PWM/1','Lower_AND/1');
sl(model,'Lower_Delay/1','Lower_AND/2');
sl(model,'Upper_AND/1','Battery_Gate_Mux/1');
sl(model,'Lower_AND/1','Battery_Gate_Mux/2');
sl(model,'Battery_Gate_Mux/1','Battery_Gate_Double/1');
sl(model,'Battery_Gate_Double/1','Battery_Leg/1');
sl(model,'Battery_Blocking/1','Battery_Leg/2');
sl(model,'Battery_Connect/1','Battery_Isolator/1');
sl(model,'Battery_Connect/1','Battery_DC_Isolator/1');

sl(model,'Vref_A/1','Internal_Vref_Mux/1');
sl(model,'Vref_B/1','Internal_Vref_Mux/2');
sl(model,'Vref_C/1','Internal_Vref_Mux/3');
sl(model,'Grid_VI/1','Synchronization_Reference_Select/1');
sl(model,'Grid_Synchronization/1','Synchronization_Reference_Select/2');
sl(model,'Internal_Vref_Mux/1','Synchronization_Reference_Select/3');
sl(model,'Vdc_Measurement/1','Vdc_Error/1');
sl(model,'Vdc_Reference/1','Vdc_Error/2');
sl(model,'Vdc_Error/1','Enable_Pref_Integrator/1');
sl(model,'Grid_Connected/1','Enable_Pref_Integrator/2');
sl(model,'Enable_Pref_Integrator/1','Pref_Proportional/1');
sl(model,'Enable_Pref_Integrator/1','Pref_Integral/1');
sl(model,'Pref_Proportional/1','Pref_PI_Sum/1');
sl(model,'Pref_Integral/1','Pref_PI_Sum/2');
sl(model,'Pref_PI_Sum/1','Pref_Saturation/1');
sl(model,'Grid_Voltage_Pu_Profile/1','Grid_Pu_Minus_One/1');
sl(model,'Grid_Pu_Minus_One/1','Reactive_Power_Coefficient/1');
sl(model,'Grid_Connected/1','FCS_Input_Mux/1');
sl(model,'Vdc_Measurement/1','FCS_Input_Mux/2');
sl(model,'Filter_VI/1','FCS_Input_Mux/3');
sl(model,'Filter_VI/2','FCS_Input_Mux/4');
sl(model,'Load_VI/2','FCS_Input_Mux/5');
sl(model,'Grid_VI/1','FCS_Input_Mux/6');
sl(model,'Synchronization_Reference_Select/1','FCS_Input_Mux/7');
sl(model,'Pref_Saturation/1','FCS_Input_Mux/8');
sl(model,'Reactive_Power_Coefficient/1','FCS_Input_Mux/9');
sl(model,'FCS_Input_Mux/1','MPVC_MPPC_FCS/1');
sl(model,'MPVC_MPPC_FCS/1','FCS_Output_Demux/1');
sl(model,'FCS_Output_Demux/1','Inverter_Gate_Enable/1');
sl(model,'Inverter_Enable/1','Inverter_Gate_Enable/2');
sl(model,'Inverter_Connect/1','Inverter_DC_Isolator/1');
sl(model,'Inverter_Gate_Enable/1','Inverter_Gate_Double/1');
sl(model,'Inverter_Gate_Double/1','Interlinking_Converter/1');

sl(model,'Load_VI/1','AC_Load_Power/1');
sl(model,'Load_VI/2','AC_Load_Power/2');
sl(model,'Grid_Connected/1','EMS_Input_Mux/1');
sl(model,'PV_Power/1','EMS_Input_Mux/2');
sl(model,'AC_Load_Power/1','EMS_Input_Mux/3');
sl(model,'DC_Load_Power/1','EMS_Input_Mux/4');
sl(model,'SOC_Integrator/1','EMS_Input_Mux/5');
sl(model,'EMS_Input_Mux/1','EMS_Fig9/1');
sl(model,'EMS_Fig9/1','EMS_Output_Demux/1');

% Log connections.
sl(model,'Vdc_Measurement/1','log_Vdc/1');
sl(model,'Vpv_Measurement/1','log_Vpv/1');
sl(model,'Ipv_Measurement/1','log_Ipv/1');
sl(model,'Ibat_Measurement/1','log_Ibat/1');
sl(model,'SOC_Integrator/1','log_SOC/1');
sl(model,'Filter_VI/1','log_Vcabc/1');
sl(model,'Filter_VI/2','log_Ifabc/1');
sl(model,'Grid_VI/1','log_Vgabc/1');
sl(model,'Grid_VI/2','log_Igabc/1');
sl(model,'Pref_Saturation/1','log_Pref/1');
sl(model,'Reactive_Power_Coefficient/1','log_Qref/1');
sl(model,'FCS_Output_Demux/1','log_Gates/1');
sl(model,'FCS_Output_Demux/2','log_FCSCost/1');
sl(model,'FCS_Output_Demux/3','log_FCSState/1');
sl(model,'EMS_Fig9/1','log_EMS/1');
sl(model,'EMS_Output_Demux/3','log_LoadShed/1');

%% Physical electrical wiring
% PV path and input capacitor.
ec(model,'PV_Array','RConn',1,'Ipv_Measurement','LConn',1);
ec(model,'Ipv_Measurement','RConn',1,'Lpv','LConn',1);
ec(model,'Lpv','RConn',1,'PV_Isolator','LConn',1);
ec(model,'PV_Isolator','RConn',1,'PV_Boost','LConn',1);
ec(model,'PV_Array','RConn',1,'Cpv','LConn',1);
ec(model,'PV_Array','RConn',2,'Cpv','RConn',1);
ec(model,'PV_Array','RConn',1,'Vpv_Measurement','LConn',1);
ec(model,'PV_Array','RConn',2,'Vpv_Measurement','LConn',2);
ec(model,'PV_Array','RConn',2,'PV_Boost','RConn',2);

% DC positive bus with commissioning isolators. They are closed in the
% paper scenario and opened only during staged validation.
ec(model,'PV_Boost','RConn',1,'PV_DC_Isolator','LConn',1);
ec(model,'PV_DC_Isolator','RConn',1,'Cdc','LConn',1);
ec(model,'Cdc','LConn',1,'Vdc_Measurement','LConn',1);
ec(model,'Cdc','LConn',1,'Idc1_Measurement','LConn',1);
ec(model,'Cdc','LConn',1,'Idc2_Measurement','LConn',1);
ec(model,'Cdc','LConn',1,'Battery_DC_Isolator','LConn',1);
ec(model,'Battery_DC_Isolator','RConn',1,'Battery_Leg','RConn',1);
ec(model,'Cdc','LConn',1,'Inverter_DC_Isolator','LConn',1);
ec(model,'Inverter_DC_Isolator','RConn',1,'Interlinking_Converter','RConn',1);
% DC negative bus.
ec(model,'PV_Array','RConn',2,'Cdc','RConn',1);
ec(model,'PV_Array','RConn',2,'Vdc_Measurement','LConn',2);
ec(model,'PV_Array','RConn',2,'DC_Load_0p6MW','RConn',1);
ec(model,'PV_Array','RConn',2,'DC_Load_1MW','RConn',1);
ec(model,'PV_Array','RConn',2,'Battery_Leg','RConn',2);
ec(model,'PV_Array','RConn',2,'Interlinking_Converter','RConn',2);
ec(model,'PV_Array','RConn',2,'DC_Ground','LConn',1);
ec(model,'Idc1_Measurement','RConn',1,'DC_Load_0p6MW','LConn',1);
ec(model,'Idc2_Measurement','RConn',1,'DC_Load_1MW','LConn',1);

% Battery midpoint -> inductor -> current sensor -> battery positive.
ec(model,'Battery_Leg','LConn',1,'Battery_Isolator','LConn',1);
ec(model,'Battery_Isolator','RConn',1,'Lbat','RConn',1);
ec(model,'Lbat','LConn',1,'Ibat_Measurement','RConn',1);
ec(model,'Ibat_Measurement','LConn',1,'Battery','LConn',1);
ec(model,'Battery','LConn',2,'PV_Array','RConn',2);

% Three-phase converter, LC filter and AC bus.
for phase = 1:3
    ec(model,'Interlinking_Converter','LConn',phase,'Filter_Lf_Rf','LConn',phase);
    ec(model,'Filter_Lf_Rf','RConn',phase,'Filter_VI','LConn',phase);
    ec(model,'Filter_VI','RConn',phase,'Filter_Cf','LConn',phase);
    ec(model,'Filter_VI','RConn',phase,'Load_VI','LConn',phase);
    ec(model,'Load_VI','RConn',phase,'AC_Load_Base','LConn',phase);
    ec(model,'Load_VI','RConn',phase,'AC_Load_Step_Breaker','LConn',phase);
    ec(model,'AC_Load_Step_Breaker','RConn',phase,'AC_Load_Step','LConn',phase);
    ec(model,'Filter_VI','RConn',phase,'Grid_Breaker','LConn',phase);
    ec(model,'Grid_Breaker','RConn',phase,'Grid_VI','LConn',phase);
    ec(model,'Grid_VI','RConn',phase,'Grid_Transformer','LConn',phase);
    ec(model,'Grid_Transformer','RConn',phase,'Utility_25kV','RConn',phase);
end

%% Annotations and save
addAnnotation(model,[20 85 465 120], ...
    'PV source + incremental-conductance MPPT + 5 kHz switching Boost (paper Fig. 2-4)',[0.09 0.35 0.60]);
addAnnotation(model,[500 120 845 150], ...
    '1200 V common DC bus, 6 mF paper capacitor, switchable DC loads',[0.09 0.35 0.60]);
addAnnotation(model,[875 130 1465 155], ...
    '300 V / 0.5 MW / 1300 Ah battery + bidirectional half bridge (paper Fig. 5 and 7)',[0.09 0.35 0.60]);
addAnnotation(model,[500 425 1010 450], ...
    'Three-phase two-level interlinking converter + Lf/Rf/Cf filter (paper Fig. 6 and 8)',[0.09 0.35 0.60]);
addAnnotation(model,[1030 715 1470 740], ...
    'Grid breaker + 690 V/25 kV, 2.5 MVA transformer + 25 kV equivalent source',[0.09 0.35 0.60]);

save_system(model,modelFile);
fprintf('Built switching template: %s\n',modelFile);
end

function sl(model,src,dst)
add_line(model,src,dst,'autorouting','on');
end

function ec(model,a,aKind,aIndex,b,bKind,bIndex)
pa = get_param([model '/' a],'PortHandles');
pb = get_param([model '/' b],'PortHandles');
add_line(model,pa.(aKind)(aIndex),pb.(bKind)(bIndex),'autorouting','on');
end

function logBlock(model,name,varName,pos)
add_block('simulink/Sinks/To Workspace',[model '/' name], ...
    'VariableName',varName,'SaveFormat','Timeseries','Position',pos);
end

function addAnnotation(model,pos,textValue,color)
ann = Simulink.Annotation(model,textValue);
ann.Position = pos;
if isnumeric(color)
    ann.ForegroundColor = 'blue';
else
    ann.ForegroundColor = color;
end
ann.FontSize = 11;
ann.FontWeight = 'bold';
end
